### ISSUE TITLE
Problem with Dependency Error

### ISSUE THREAD

**Issue by viv-b** [MattKevan/Jekyll-MiniMagick-new#1]
Hi Matt,

I'm very new to the whole Ruby/Jekyll ecosystem.  I'm using CloudCannon as my UI for Jekyll and it seems really great. Just trying to figure out a straight-forward way to create thumbnails and smaller versions of images and stumbled across your Github repository. It looks like what I am after :)

However, I'm having a bit of trouble getting it to work and wondered if you could spare a moment to see if you know what my issue is. I suspect I'm missing something obvious... I have done the following:

In my root, created folder '_plugins'.  Within that I placed jekyll_minimagick.rb

In my '_config.yml' I have the following:

```gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"
  - "rmagick"
  - "jekyll-minimagick"

mini_magick:
    thumbnail: # Preset name
        source: images/originals # source directory - change this to whatever you want
        destination: images/thumbnail # generated destination directory
        resize: "100x70^" # standard imagemagick options - you can chain multiple commands
        gravity: "center"
        extent: "100x70"
```
My 'gemfile' is:

```source 'https://rubygems.org'

gem 'jekyll', '3.3.1'

group :jekyll_plugins do
	gem 'jekyll-feed', '0.6.0'
	gem 'jekyll-seo-tag', '2.0.0'
	gem 'jekyll-paginate', '1.1.0'
	gem 'jekyll-archives', '2.1.1'
	gem 'rmagick', '2.16.0'
end
```

But I get this error:

*Dependency Error: Yikes! It looks like you don't have elegant-hummingbird.cloudvent.net/_plugins/jekyll_minimagick.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- mini_magick' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!*

Am I missing something very simple here?

**Comment by MattKevan** [comment]
Hi Viv,

I haven't used CloudCannon (though it looks like a really cool service) so I don't know exactly what their environment is like, but it could be that you also need the mini_magick gem.

Try adding `gem 'mini_magick'` to your Gemfile and see what happens. Also, I don't think you need rmagick as mini_magick is a replacement for it.

Matt

**Comment by viv-b** [comment]
Hi Matt,

Thanks very much for your prompt reply, I really appreciate it.  Yes that did seem to get rid of that build error. I'm getting another error now, but I think that is ColudCannon related, so I'm checking that one out and I'll let you know.

Just a note that on your website, in case you weren't aware, the email given for contacting bounces back to me with an email doesn't exist message.

Cheers, Viv.
