### ISSUE TITLE
problem in Jekyll build

### ISSUE THREAD

**Issue by mahdiit** [MattKevan/Jekyll-MiniMagick-new#2]
i copy file to plugin directory and also set config but when i call 
`jekyll build`

get following error:

  Dependency Error: Yikes! It looks like you don't have /_plugins/jekyll_minimagick.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- mini_magick' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

installing `gem install mini_magick` but nothing changed

**Comment by 888ba8** [comment]
@mahdiit @MattKevan I have the following problem when I try to build:

`.../_plugins/jekyll_minimagick.rb:7: syntax error, unexpected '<' (SyntaxError)`

See also https://talk.jekyllrb.com/t/plugins-jekyll-minimagick-rb-syntax-error-unexpected-syntaxerror/5477

Thank you for any clarifications!
